apiVersion: v1
kind: Service
metadata:
  labels:
    app: wh-main-app
  name: wh-main-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30009
  selector:
    app: wh-main-app